// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZDNsue_x54TsfkpbRNNNYL30cKRvdYw',
    appId: '1:1016726824660:web:1cddbeac4256778ff7bd41',
    messagingSenderId: '1016726824660',
    projectId: 'rucheiot',
    authDomain: 'rucheiot.firebaseapp.com',
    databaseURL: 'https://rucheiot-default-rtdb.firebaseio.com',
    storageBucket: 'rucheiot.firebasestorage.app',
    measurementId: 'G-TY1V4118V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0VIJDtUbwBrn4_dxn60dqHNXG0lKnnA',
    appId: '1:1016726824660:android:7a5114d8f1a4efe0f7bd41',
    messagingSenderId: '1016726824660',
    projectId: 'rucheiot',
    databaseURL: 'https://rucheiot-default-rtdb.firebaseio.com',
    storageBucket: 'rucheiot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdJSP57f4mSTMBofpn7jhncNvMh53PBWo',
    appId: '1:1016726824660:ios:c3503fc9baeda41bf7bd41',
    messagingSenderId: '1016726824660',
    projectId: 'rucheiot',
    databaseURL: 'https://rucheiot-default-rtdb.firebaseio.com',
    storageBucket: 'rucheiot.firebasestorage.app',
    iosBundleId: 'com.example.smartBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdJSP57f4mSTMBofpn7jhncNvMh53PBWo',
    appId: '1:1016726824660:ios:c3503fc9baeda41bf7bd41',
    messagingSenderId: '1016726824660',
    projectId: 'rucheiot',
    databaseURL: 'https://rucheiot-default-rtdb.firebaseio.com',
    storageBucket: 'rucheiot.firebasestorage.app',
    iosBundleId: 'com.example.smartBee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ZDNsue_x54TsfkpbRNNNYL30cKRvdYw',
    appId: '1:1016726824660:web:bff02f4e97be01e5f7bd41',
    messagingSenderId: '1016726824660',
    projectId: 'rucheiot',
    authDomain: 'rucheiot.firebaseapp.com',
    databaseURL: 'https://rucheiot-default-rtdb.firebaseio.com',
    storageBucket: 'rucheiot.firebasestorage.app',
    measurementId: 'G-LRLY06D9XZ',
  );
}
